SELECT * FROM tab;

SELECT * FROM users;

SELECT * FROM tasks;
SELECT * FROM task_types;

SELECT * FROM TASK_STATUSES;
SELECT * FROM COMMON_CODE;

UPDATE TASK_STATUSES 
set task_status_id = 5
WHERE task_status_id = 6;

COMMIT;

SELECT
	P.PROJECT_ID,
	P.PARENT_PROJECT_ID,
    (SELECT PROJECT_NAME FROM PROJECTS P2 WHERE P2.PARENT_PROJECT_ID=P.PROJECT_ID) AS PARENT_PROJECT_NAME,
	P.PROJECT_NAME,
    P.END_DATE,
    P.PM_USER_ID,
	AVG(NVL(T.PROGRESS_RATE,0)) AS PROGRESS_RATE
FROM PROJECTS P JOIN TASKS T
ON P.PROJECT_ID = T.PROJECT_ID
GROUP BY 
	P.PARENT_PROJECT_ID,
	P.PROJECT_ID, 
	P.PROJECT_NAME, 
	P.END_DATE, 
	P.PM_USER_ID 
ORDER BY P.PARENT_PROJECT_ID;

SELECT * FROM projects;

SELECT
	P.PARENT_PROJECT_ID,
	P2.PROJECT_NAME AS PARENT_PROJECT_NAME,
	AVG(NVL(T.PROGRESS_RATE,0)) AS PROGRESS_RATE
FROM PROJECTS P
LEFT JOIN PROJECTS P2
	ON P.PARENT_PROJECT_ID = P2.PROJECT_ID 
LEFT JOIN TASKS T
	ON P.PROJECT_ID = T.PROJECT_ID
WHERE P.PARENT_PROJECT_ID IS NOT NULL
GROUP BY
	P.PARENT_PROJECT_ID ,
	P2.PROJECT_NAME
ORDER BY
	P.PARENT_PROJECT_ID;

--프로젝트 대쉬보드 목록 띄우기 쿼리
    SELECT
        P2.PROJECT_ID AS projectId,
        P2.PROJECT_NAME AS parentProjectName,
        P2.END_DATE AS endDate,
        P2.PM_USER_ID AS pmUserId,
        P2.PL_USER_ID AS plUserId,
        ROUND(AVG(NVL(T.PROGRESS_RATE, 0)), 0) AS progressRate
    FROM PROJECTS P
    JOIN PROJECTS P2
        ON P.PARENT_PROJECT_ID = P2.PROJECT_ID
    LEFT JOIN TASKS T
        ON P.PROJECT_ID = T.PROJECT_ID
    GROUP BY
        P2.PROJECT_ID,
        P2.PROJECT_NAME,
        P2.END_DATE,
        P2.PM_USER_ID,
        P2.PL_USER_ID
    ORDER BY
        P2.PROJECT_ID;

SELECT * FROM projects;
SELECT * FROM tasks;

SELECT
	t.task_status_id,
	t.project_id,
	t.ASSIGNEE_USER_ID,
	p.project_name
FROM tasks t
JOIN projects p 
	ON p.project_id = t.project_id;
